// tools/build-frames — Phase 2 of the sprite pipeline.
//
// Reads pre-sliced frame PNGs from /tmp/build-frames/ (produced by slice.py),
// renders each one with chafa in braille mode (monochrome), and emits Go source
// files under internal/ascii/<species>_<variant>_<state>.go
//
// Frames are already tight-cropped by slice.py (transparent margins removed),
// so chafa gets maximum pixel density for its output size.
//
// Usage:
//
//	python3 tools/build-frames/slice.py   # slice + crop sprite sheets
//	go run ./tools/build-frames           # render + emit Go files
package main

import (
	"bytes"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
	"text/template"
	"time"
)

const (
	framesRoot = "/tmp/build-frames"
	outPkg     = "internal/ascii"

	// chafa render size.
	// 48 wide gives good horizontal detail; 24 tall accommodates the front-facing
	// sprite aspect ratio (wider than tall after crop).
	chafaW = "48"
	chafaH = "24"
)

// frameDelays per state. Walk/idle are snappier; eat is slow (grazing).
var stateDelays = map[string]time.Duration{
	"idle": 600 * time.Millisecond,
	"walk": 180 * time.Millisecond,
	"eat":  400 * time.Millisecond,
}

func defaultDelay(state string) time.Duration {
	if d, ok := stateDelays[state]; ok {
		return d
	}
	return 300 * time.Millisecond
}

var goTmpl = template.Must(template.New("frames").Parse(`// Code generated by tools/build-frames. DO NOT EDIT.
package ascii

import "time"

// {{.VarPrefix}}Frames contains the animation frames for the {{.Species}} {{.Variant}} in {{.State}} state.
var {{.VarPrefix}}Frames = []string{
{{- range .Frames}}
	` + "`" + `{{.}}` + "`" + `,
{{- end}}
}

// {{.VarPrefix}}Delays contains the per-frame display durations.
var {{.VarPrefix}}Delays = []time.Duration{
{{- range .Delays}}
	{{.}},
{{- end}}
}
`))

type tmplData struct {
	VarPrefix string
	Species   string
	Variant   string
	State     string
	Frames    []string
	Delays    []string
}

func renderFrame(pngPath string) (string, error) {
	cmd := exec.Command("chafa",
		"--symbols", "braille", // braille dots: 8 sub-pixels per cell, maximum detail
		"--size", chafaW+"x"+chafaH,
		"--colors", "none", // monochrome — no ANSI color codes, pure dot density
		pngPath,
	)
	var out bytes.Buffer
	cmd.Stdout = &out
	cmd.Stderr = os.Stderr
	if err := cmd.Run(); err != nil {
		return "", fmt.Errorf("chafa %s: %w", pngPath, err)
	}
	// Trim trailing newline; internal newlines stay (multiline frame string).
	return strings.TrimRight(out.String(), "\n"), nil
}

func titleCase(s string) string {
	if len(s) == 0 {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}

// varPrefix turns "horse palomino walk" → "HorsePalominoWalk"
func varPrefix(species, variant, state string) string {
	return titleCase(species) + titleCase(variant) + titleCase(state)
}

func main() {
	// Find all animal×state combos under framesRoot.
	animalDirs, err := os.ReadDir(framesRoot)
	if err != nil {
		fmt.Fprintf(os.Stderr, "error reading %s: %v\n(did you run slice.py first?)\n", framesRoot, err)
		os.Exit(1)
	}

	// Determine repo root (cwd when invoked via go run ./tools/build-frames/).
	repoRoot, err := filepath.Abs(filepath.Join("."))
	if err != nil {
		fmt.Fprintf(os.Stderr, "cannot resolve repo root: %v\n", err)
		os.Exit(1)
	}
	outDir := filepath.Join(repoRoot, outPkg)
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		fmt.Fprintf(os.Stderr, "cannot create %s: %v\n", outDir, err)
		os.Exit(1)
	}

	total := 0
	for _, animalEntry := range animalDirs {
		if !animalEntry.IsDir() {
			continue
		}
		animalKey := animalEntry.Name() // e.g. "horse_palomino"
		parts := strings.SplitN(animalKey, "_", 2)
		if len(parts) != 2 {
			fmt.Fprintf(os.Stderr, "skipping unexpected dir name: %s\n", animalKey)
			continue
		}
		species := parts[0]
		variant := parts[1]

		stateDirs, err := os.ReadDir(filepath.Join(framesRoot, animalKey))
		if err != nil {
			fmt.Fprintf(os.Stderr, "cannot read states for %s: %v\n", animalKey, err)
			continue
		}

		for _, stateEntry := range stateDirs {
			if !stateEntry.IsDir() {
				continue
			}
			state := stateEntry.Name()
			stateDir := filepath.Join(framesRoot, animalKey, state)

			// Collect frame PNGs in sorted order.
			framePaths, err := filepath.Glob(filepath.Join(stateDir, "frame_*.png"))
			if err != nil || len(framePaths) == 0 {
				fmt.Fprintf(os.Stderr, "no frames found in %s\n", stateDir)
				continue
			}
			sort.Strings(framePaths)

			var renderedFrames []string
			for _, fp := range framePaths {
				rendered, err := renderFrame(fp)
				if err != nil {
					fmt.Fprintf(os.Stderr, "render error: %v\n", err)
					os.Exit(1)
				}
				renderedFrames = append(renderedFrames, rendered)
			}

			// Build delay slice — same delay for all frames in a state.
			delay := defaultDelay(state)
			var delays []string
			for range renderedFrames {
				delays = append(delays, fmt.Sprintf("%d*time.Millisecond", delay.Milliseconds()))
			}

			prefix := varPrefix(species, variant, state)
			data := tmplData{
				VarPrefix: prefix,
				Species:   species,
				Variant:   variant,
				State:     state,
				Frames:    renderedFrames,
				Delays:    delays,
			}

			var buf bytes.Buffer
			if err := goTmpl.Execute(&buf, data); err != nil {
				fmt.Fprintf(os.Stderr, "template error for %s: %v\n", prefix, err)
				os.Exit(1)
			}

			outFile := filepath.Join(outDir, fmt.Sprintf("%s_%s_%s.go", species, variant, state))
			if err := os.WriteFile(outFile, buf.Bytes(), 0o644); err != nil {
				fmt.Fprintf(os.Stderr, "write error %s: %v\n", outFile, err)
				os.Exit(1)
			}

			fmt.Printf("  wrote %s (%d frames)\n", filepath.Base(outFile), len(renderedFrames))
			total++
		}
	}

	fmt.Printf("\nDone — %d files written to %s/\n", total, outPkg)
}
