// Code generated by tools/build-frames. DO NOT EDIT.
package ascii

import "time"

// BullBrownIdleFrames contains the animation frames for the bull brown in idle state.
var BullBrownIdleFrames = []string{
	`                            
                            
                            
                            
                            
        ▂▃▄▆▆▆▆▆▆▆▆▖▁    ▃▖ 
     ▁▆▇████████████▙▅▗▄▟█▍ 
     ▔██▐████████████████▌  
    ▕▏█▏▐█████████████▜██▚▎ 
    ▕▏▝  ▐██▀▀▀▛████▀██▃    
        ▕▇▛▍  ▔ ▕▜█▍▔▜██▋   
        ▕█▌      ▝█▎  ▝▀▘   
         ▔▘       ▔▁        
          ▔       ▔▔        `,
}

// BullBrownIdleDelays contains the per-frame display durations.
var BullBrownIdleDelays = []time.Duration{
	600*time.Millisecond,
}
