// Code generated by tools/build-frames. DO NOT EDIT.
package ascii

import "time"

// BullBrownWalkFrames contains the animation frames for the bull brown in walk state.
var BullBrownWalkFrames = []string{
	`                            
                            
                            
                            
                            
          ▁▂▃▃▃▃▃▃▂▁        
      ▁▄▆▇█████████▙▏▁  ▗▇▍ 
     ▕███████████████████▛▘ 
      █▀▐████████████████▅  
      ▜▔▐███▜▜▜███████▄▔▔▔  
       ▗▟█▀▔ ▔▔▔▔▝██▎▜█▙▖   
       ▜▛▘        ▝█▏▔▜█▋   
                   ▔▁       
                    ▔       `,
	`                            
                            
                            
                            
                            
        ▂▃▄▆▆▆▆▆▆▆▆▖▁    ▃▖ 
     ▁▆▇████████████▙▅▗▄▟█▍ 
     ▔██▐████████████████▌  
    ▕▏█▏▐█████████████▜██▚▎ 
    ▕▏▝  ▐██▀▀▀▛████▀██▃    
        ▕▇▛▍  ▔ ▕▜█▍▔▜██▋   
        ▕█▌      ▝█▎  ▝▀▘   
         ▔▘       ▔▁        
          ▔       ▔▔        `,
	`                            
                            
                            
                            
                            
          ▁▃▃▃▃▃▃▃▂▁        
      ▁▄▇▇█████████▇▖▁  ▗▇▍ 
     ▕███████████████████▛▘ 
      █▀▐████████████████▅▖ 
    ▕▏▜▔▔▜████████████▄▔▔▔  
   ▕▔ ▔   ▜█▍▔▔▝██▌▔▔███▖   
          ▝█▎  ▕▝▀   ▔▜█▋   
                            
                            `,
}

// BullBrownWalkDelays contains the per-frame display durations.
var BullBrownWalkDelays = []time.Duration{
	180*time.Millisecond,
	180*time.Millisecond,
	180*time.Millisecond,
}
