// Code generated by tools/build-frames. DO NOT EDIT.
package ascii

import "time"

// BullBrownEatFrames contains the animation frames for the bull brown in eat state.
var BullBrownEatFrames = []string{
	`                            
                            
                            
                            
                            
       ▁▂▄▆▆▆▆▆▆▆▆▆▖▁    ▃▖ 
      ▟█████████████▙▅▗▄▇█▍ 
     ▕██▐████████████████▌  
    ▕▏█▔▐█████████████▜██▚▎ 
     ▕▔  ▜██▀▀▜▜████▀██▃    
        ▗▟█▍    ▔▜█▌▔▜██▋   
        ▕█▋      ▐█▍  ▝▀▘   
         ▝▘       ▝▁        
         ▔▔       ▔▔        `,
	`                            
                            
                            
                            
                            
        ▂▃▄▆▆▆▆▆▆▆▆▖▁       
     ▁▆▇████████████▙▁  ▗▇▍ 
     ▔██▐████████████████▛▘ 
    ▕▏█▏▐████████████████▅▖ 
    ▕▏▝  ▐██▀▀▀▛████▜█▄▔▔▔  
    ▕▏  ▕▇█▍  ▔ ▕▜█▍▔███▄   
        ▕█▌      ▝█▍ ▔▜█▋   
         ▔▘       ▔▁        
          ▔       ▔▔        `,
	`                            
                            
                            
                            
                            
        ▃▄▆▆▆▆▆▆▆▆▃▁        
      ▇▇████████████▇    ▄▖ 
     ▝████████████████▅▅██▍ 
    ▐▎█▉▝████████████████▌  
    ▐▎▔▉▕▟███▜█████████▛▀▜▎ 
    ▝▏ ▔▕█▛▘  ▔  ▜█▛███▙▁   
        ▕█▋      ▐█▍ ▜██▋   
         ▝▃       ▝▃  ▀▀▘   
         ▔▔       ▔▔        `,
}

// BullBrownEatDelays contains the per-frame display durations.
var BullBrownEatDelays = []time.Duration{
	400*time.Millisecond,
	400*time.Millisecond,
	400*time.Millisecond,
}
