// Code generated by tools/build-frames. DO NOT EDIT.
package ascii

import "time"

// CatTabbyWalkFrames contains the animation frames for the cat tabby in walk state.
var CatTabbyWalkFrames = []string{
	`                            
                            
                            
                            
                            
                            
                            
                     ▁      
       ▕▆        ▁  ▃▇      
       ▕█▄▁ ▁▁   ▐▇▇██      
        ▔▜█▙█▍█▄▇█████      
         ▝███▛▀▜███▛▀▔      
         ▐█▍ ▁   ▝█▆▏       
          ▔▔ ▔    ▔▔        `,
	`                            
                            
                            
                            
                            
                            
                            
        ▁            ▁      
       ▕▉        ▂▂▂▆█      
        ▀▙▃▃▖▄▁▃▗▟███▉      
         ▐██▙█▟█▟████▛      
          ▜█▀▔▔▀▜█▛▎        
        ▕▏▐▃     ▐▙▏        
           ▔      ▔         `,
	`                            
                            
                            
                            
                            
                            
                            
                            
       ▕▆           ▂▆      
       ▕▜▃       ▐▇▇██      
         ▜█▙█▎█▗▙▟███▉      
          ▝▜██▀▜█▛▀▀▀       
            █▇ ▐▙▖          
            ▔   ▔▔          `,
}

// CatTabbyWalkDelays contains the per-frame display durations.
var CatTabbyWalkDelays = []time.Duration{
	180*time.Millisecond,
	180*time.Millisecond,
	180*time.Millisecond,
}
