// Code generated by tools/build-frames. DO NOT EDIT.
package ascii

import "time"

// CatGrayIdleFrames contains the animation frames for the cat gray in idle state.
var CatGrayIdleFrames = []string{
	`                            
                            
                            
                            
                            
                            
                            
        ▁            ▁      
       ▕▊       ▕▂▂▂▆█      
        ▀▙▃▃▃▄▄▃▁▟███▉      
         ▐███████████▛      
          ▜█▛▔▔▀▜█▛▎        
        ▕▏▐▙▖    ▐▙▎        
          ▔▔▔     ▔▔        `,
}

// CatGrayIdleDelays contains the per-frame display durations.
var CatGrayIdleDelays = []time.Duration{
	600*time.Millisecond,
}
