// Code generated by tools/build-frames. DO NOT EDIT.
package ascii

import "time"

// CatGrayWalkFrames contains the animation frames for the cat gray in walk state.
var CatGrayWalkFrames = []string{
	`                            
                            
                            
                            
                            
                            
                            
        ▁            ▁      
       ▗▆▏      ▕▁  ▃▇▏     
       ▕█▄▁▁▁▁▁ ▕▇▇▇██      
        ▕▜██████▅█████      
         ▐███▛▜████▛▀▔      
         ▐█▌ ▁   ▝█▆▏       
          ▔▔ ▔    ▔▔        `,
	`                            
                            
                            
                            
                            
                            
                            
        ▁            ▁      
       ▕▊       ▕▂▂▂▆█      
        ▀▙▃▃▃▄▄▃▁▟███▉      
         ▐███████████▛      
          ▜█▛▔▔▀▜█▛▎        
        ▕▏▐▙▖    ▐▙▎        
          ▔▔▔     ▔▔        `,
	`                            
                            
                            
                            
                            
                            
                            
                     ▁      
       ▕▊        ▁  ▂▇      
       ▕▜▃  ▁▁▁  ▜▇▇██      
         ▜█████▇▅█████      
          ▀▀██▀▜█▛▀▀▀▔      
            █▇ ▐█▖          
            ▔  ▔▔▔          `,
}

// CatGrayWalkDelays contains the per-frame display durations.
var CatGrayWalkDelays = []time.Duration{
	180*time.Millisecond,
	180*time.Millisecond,
	180*time.Millisecond,
}
