// Code generated by tools/build-frames. DO NOT EDIT.
package ascii

import "time"

// CatSiameseIdleFrames contains the animation frames for the cat siamese in idle state.
var CatSiameseIdleFrames = []string{
	`                            
                            
                            
                            
                            
                            
                            
       ▁▁            ▁      
       ▕▊       ▝▚▂▂▂▉      
        ▔▘▃▃▆▆▃▃▃█████      
         ▝████████████      
          ▐██▀▀▀▜█▛▏        
        ▕▋▝▃▎   ▖▝▃▎        
           ▔▔   ▔ ▔▔        `,
}

// CatSiameseIdleDelays contains the per-frame display durations.
var CatSiameseIdleDelays = []time.Duration{
	600*time.Millisecond,
}
