// Code generated by tools/build-frames. DO NOT EDIT.
package ascii

import "time"

// CatSiameseWalkFrames contains the animation frames for the cat siamese in walk state.
var CatSiameseWalkFrames = []string{
	`                            
                            
                            
                            
                            
                            
                            
                            
       ▕▊       ▕▁   ▁      
       ▕▘   ▃▃▃  ▜▇▇▇▅      
         ▗████████████      
         ▝███▛▜███▋▀▀▔      
         ▝▘▖    ▔▔▔▕▏       
          ▔▔                `,
	`                            
                            
                            
                            
                            
                            
                            
       ▁▁            ▁      
       ▕▊       ▝▚▂▂▂▉      
        ▔▘▃▃▆▆▃▃▃█████      
         ▝████████████      
          ▐██▀▀▀▜█▛▏        
        ▕▋▝▃▎   ▖▝▃▎        
           ▔▔   ▔ ▔▔        `,
	`                            
                            
                            
                            
                            
                            
                            
                            
       ▕▊       ▗▖   ▅      
       ▕▚▖  ▃▃▃  ▜▇▇▇█      
          ▗███████████      
        ▖ ▝████████▀▀▀      
        ▘  ▗▟▖▕▆▔▘          
           ▔▔▔ ▔▔           `,
}

// CatSiameseWalkDelays contains the per-frame display durations.
var CatSiameseWalkDelays = []time.Duration{
	180*time.Millisecond,
	180*time.Millisecond,
	180*time.Millisecond,
}
