// Code generated by tools/build-frames. DO NOT EDIT.
package ascii

import "time"

// CatBicolorWalkFrames contains the animation frames for the cat bicolor in walk state.
var CatBicolorWalkFrames = []string{
	`                            
                            
                            
                            
                            
                            
                            
                            
       ▕▆       ▕▁  ▂▆      
       ▕█▙       ▜▇▇█▉      
        ▝▜██████▅█████      
         ▐███▛▜████▛▀▔      
         ▐█▌     ▝█▆▏       
          ▔▔      ▔▔        `,
	`                            
                            
                            
                            
                            
                            
                            
        ▁            ▁      
       ▕▉▂      ▕▂▂▂▆█      
        ▜█▃▃▃▃▃▃▁▟███▉      
         ▐███████████▛      
          ▜█▛▏▔▀▜█▛▘        
        ▕▏▐▙▎    ▐▙▖        
          ▔▔     ▔▔         `,
	`                            
                            
                            
                            
                            
                            
                            
                            
       ▕▆        ▁  ▂▆      
       ▕█▙       ▐▇▇█▉      
        ▔▜██████▅█████      
          ▝▀██▀▜█▛▀▀▀▔      
            █▆ ▐█▖          
            ▔   ▔▔          `,
}

// CatBicolorWalkDelays contains the per-frame display durations.
var CatBicolorWalkDelays = []time.Duration{
	180*time.Millisecond,
	180*time.Millisecond,
	180*time.Millisecond,
}
