// Code generated by tools/build-frames. DO NOT EDIT.
package ascii

import "time"

// ChickenWhiteWalkFrames contains the animation frames for the chicken white in walk state.
var ChickenWhiteWalkFrames = []string{
	`                            
                            
                            
                            
                            
                            
                            
                            
              ▁             
             ▃▃▃▃           
         ▁▁▄███▛▀▘          
        ▐██▌▅███▍           
         ▝▜▇▀██▊            
          ▔▔  ▔▔            `,
	`                            
                            
                            
                            
                            
                            
                            
                            
                            
            ▃▇▇▇▇▖          
        ▗▄▄▞▜██▙▔▔          
        ▝▜█▙████▘           
          ▔▔▎▔▔             
           ▔  ▔             `,
	`                            
                            
                            
                            
                            
                            
                            
                            
              ▁             
             ▃▃▃▃           
         ▁▁▄███▛▀▘          
        ▐██▌▅███▍           
         ▝▜▇███▘            
            ▔               `,
}

// ChickenWhiteWalkDelays contains the per-frame display durations.
var ChickenWhiteWalkDelays = []time.Duration{
	180*time.Millisecond,
	180*time.Millisecond,
	180*time.Millisecond,
}
