// Code generated by tools/build-frames. DO NOT EDIT.
package ascii

import "time"

// CowHolsteinIdleFrames contains the animation frames for the cow holstein in idle state.
var CowHolsteinIdleFrames = []string{
	`                            
                            
                            
                            
                     ▁      
       ▁▁▃▆▆▆▆▏▁▁▁▁▁▃▇▃▃▖   
     ▄▅▏▁▔██████▅▁▁▅████▘   
     ██▇▂▄███▛▜███████▅     
     █▛▜████▌▁▁▁▟█████▂▂    
   ▕▏█▏▕▜███▜▏▕▟██▌▝▜██▊    
     ▀ ▕█▛▘    ▐█▋   ▔▔▔    
      ▅▕█▊     ▕█▋          
        ▀▘      ▝▘          
         ▔       ▔          `,
}

// CowHolsteinIdleDelays contains the per-frame display durations.
var CowHolsteinIdleDelays = []time.Duration{
	600*time.Millisecond,
}
