// Code generated by tools/build-frames. DO NOT EDIT.
package ascii

import "time"

// CowHolsteinWalkFrames contains the animation frames for the cow holstein in walk state.
var CowHolsteinWalkFrames = []string{
	`                            
                            
                            
                            
                            
          ▃▃▃▃       ▃      
         ▐████▙▄    ▇█▇▇▋   
     ██▁ ▁███████▅▅███▛▘    
     █▛█▆███▛▎ ▝▜█████▀     
     ▔ ▟████▙▏ ▐███▀██▇▊    
      ▕██▛▔▔▔  ▝▜█▙▎▔▀▀▘    
      ▀█▊        ▐█▙▏       
                  ▔         
                            `,
	`                            
                            
                            
                            
                     ▁      
       ▁▁▃▆▆▆▆▏▁▁▁▁▁▃▇▃▃▖   
     ▄▅▏▁▔██████▅▁▁▅████▘   
     ██▇▂▄███▛▜███████▅     
     █▛▜████▌▁▁▁▟█████▂▂    
   ▕▏█▏▕▜███▜▏▕▟██▌▝▜██▊    
     ▀ ▕█▛▘    ▐█▋   ▔▔▔    
      ▅▕█▊     ▕█▋          
        ▀▘      ▝▘          
         ▔       ▔          `,
	`                            
                            
                            
                            
                            
         ▁▃▃▃▃▁▁     ▄      
      ▁▁▁▐████▙▅▁▁▁▁▇█▇▇▋   
    ▁██▂▁▁███████▆▆███▛▀    
    ████▇███▛▎▁▝██████▀     
    █▎▔▀████▙▏▔▐██▛▜███▊    
   ▐▍   ▝██▌▔▔▗▟█▛  ▔▀▀▀    
      ▔▅ ▐█▍  ▜█▀           
                            
                            `,
}

// CowHolsteinWalkDelays contains the per-frame display durations.
var CowHolsteinWalkDelays = []time.Duration{
	180*time.Millisecond,
	180*time.Millisecond,
	180*time.Millisecond,
}
