// Code generated by tools/build-frames. DO NOT EDIT.
package ascii

import "time"

// CowHolsteinEatFrames contains the animation frames for the cow holstein in eat state.
var CowHolsteinEatFrames = []string{
	`                            
                            
                            
                            
                            
       ▁▁▐▆▆▆▆▅▄▁▁   ▁      
     ▄▅▏▁▁▜█████▇▅▇▇▄█▄▄▖   
     ███▆███▛▎▁▝███████▛▘   
     ▜▃▀▜███▙▏▁▗██████▆     
   ▕▏ ▔ ▐█▛▀▀▔▕███▜███▃▃    
      ▀▕█▊     ▐█▋ ▔▜██▊    
      ▅▕█▊     ▕█▋    ▔     
        ▔▘      ▝▘          
         ▔       ▔          `,
	`                            
                            
                            
                            
                            
         ▗▆▆▆▆▏             
     ▄▄▏ ▔█████▇▄  ▄▏▄      
     ██▆▁▄███▛▀▜████████▋   
     █▀▜████▍  ▁▟█████▉▘    
     █▏▕▜██▛▀▏▕▟██████▘     
     ▀ ▕█▛▘    ▐█▋ ▀███▊    
      ▅▕█▋     ▕█▋   ▀▀▘    
        ▔▘      ▝▘          
                            `,
	`                            
                            
                            
                            
                            
          ▃▃▃▃              
         ▐████▙▄            
    ▁██▁ ▁███████▅▅█▅█▅▅▋   
    ▟███▆███▛▎ ▝▜██████▛▘   
    ▜▎▔▕████▙▏ ▐██████▀     
   ▐▍  ▕▟█▛▔▔ ▕▜██▀███▄▖    
      ▂▕█▋     ▐█▋  ▀██▊    
      ▔ ▔▘      ▔▘          
                            `,
}

// CowHolsteinEatDelays contains the per-frame display durations.
var CowHolsteinEatDelays = []time.Duration{
	400*time.Millisecond,
	400*time.Millisecond,
	400*time.Millisecond,
}
