// Code generated by tools/build-frames. DO NOT EDIT.
package ascii

import "time"

// DogBeagleWalkFrames contains the animation frames for the dog beagle in walk state.
var DogBeagleWalkFrames = []string{
	`                            
                            
                            
                            
                            
                            
                            
        ▁                   
       ▗▉     ▁▅▆▖▁▁        
       ▐█▃ ▁▁ ▝█▊▕▁▏▇▏      
        ▀████████▖▔▄██      
        ▂▅███████▛▘▔▀▀      
        ▜█▋    ▝▜▆▎         
         ▔▔     ▔▔          `,
	`                            
                            
                            
                            
                            
                            
                            
       ▁▂      ▁▁▁          
       ▐▉     ▗█▊▘▁▏▂       
       ▕█▙▃▄▄▃▃█▊▕▁▏█▃      
        ▔▀▜██████▙▖▀██      
          ▂██▀▀██▋          
       ▕▏▐██▍ ▕▟█▃          
          ▔▔▔  ▔▔▔          `,
	`                            
                            
                            
                            
                            
                            
                            
        ▁                   
       ▗▉     ▁▅▆▖▁▁        
       ▐█▃ ▁▁ ▝█▊▕▁▏▇▏      
        ▀████████▖▔▄██      
          ▐██████▀▘▔▀▀      
           █▇▎▐█▋           
           ▔  ▔▔▔           `,
}

// DogBeagleWalkDelays contains the per-frame display durations.
var DogBeagleWalkDelays = []time.Duration{
	180*time.Millisecond,
	180*time.Millisecond,
	180*time.Millisecond,
}
