// Code generated by tools/build-frames. DO NOT EDIT.
package ascii

import "time"

// DogGoldenIdleFrames contains the animation frames for the dog golden in idle state.
var DogGoldenIdleFrames = []string{
	`                            
                            
                            
                            
                            
                            
                            
        ▁      ▁▁▁▁▁        
       ▕▊     ▗█▊▜██▆       
       ▕█▙▃▃▄▃▟█▊▐█▍█▃      
        ▔▀▜██████▙▖▀██      
          ▂██▀▀██▋          
         ▐██▍ ▕▟█▖          
          ▔▔▔  ▔▔▔          `,
}

// DogGoldenIdleDelays contains the per-frame display durations.
var DogGoldenIdleDelays = []time.Duration{
	600*time.Millisecond,
}
