// Code generated by tools/build-frames. DO NOT EDIT.
package ascii

import "time"

// DogGoldenWalkFrames contains the animation frames for the dog golden in walk state.
var DogGoldenWalkFrames = []string{
	`                            
                            
                            
                            
                            
                            
                            
                            
        ▃     ▁▄▆▂▅▆▂       
       ▕█▃  ▁ ▝█▊▐█▛█▏      
        ▀███████▙▞▀▙██      
        ▂▅▟██████▛▘▔▀▀      
        ▜█▌    ▝▜▆▍         
         ▔▔      ▔          `,
	`                            
                            
                            
                            
                            
                            
                            
        ▁      ▁▁▁▁▁        
       ▕▊     ▗█▊▜██▆       
       ▕█▙▃▃▄▃▟█▊▐█▍█▃      
        ▔▀▜██████▙▖▀██      
          ▂██▀▀██▋          
         ▐██▍ ▕▟█▖          
          ▔▔▔  ▔▔▔          `,
	`                            
                            
                            
                            
                            
                            
                            
                            
        ▃     ▁▅▆▂▅▆▂       
       ▕█▃ ▁▁ ▝█▊▐█▛█▏      
        ▀███████▙▞▀▙██      
           ██████▀▘▔▀▀      
          ▕█▇▏▕█▋           
           ▔   ▔▔           `,
}

// DogGoldenWalkDelays contains the per-frame display durations.
var DogGoldenWalkDelays = []time.Duration{
	180*time.Millisecond,
	180*time.Millisecond,
	180*time.Millisecond,
}
