// Code generated by tools/build-frames. DO NOT EDIT.
package ascii

import "time"

// DogBrownIdleFrames contains the animation frames for the dog brown in idle state.
var DogBrownIdleFrames = []string{
	`                            
                            
                            
                            
                            
                            
                            
       ▁     ▁▁  ▁▁         
      ▕▇▁ ▁▁ ▔▂▅▅▐█▍        
       ▀▀▃▇█▇▇███▙▟█▏       
         ▝██▛███▋▀▀█▎       
       ▁▔▐█▋▏ ▜█▏           
       ▔ ▝▀▘  ▝▀▘           
                            `,
}

// DogBrownIdleDelays contains the per-frame display durations.
var DogBrownIdleDelays = []time.Duration{
	600*time.Millisecond,
}
