// Code generated by tools/build-frames. DO NOT EDIT.
package ascii

import "time"

// DogScottieWalkFrames contains the animation frames for the dog scottie in walk state.
var DogScottieWalkFrames = []string{
	`                            
                            
                            
                            
                            
                            
                            
                   ▁        
       ▁     ▆▁  ▂▆▍        
      ▕█▁▁▁▁▁▝▗▆▇██▍        
       ▀▜▜▅█████████▎       
         ▕▜█▛███▔▐▛█▏       
         ▕▜▛▎▕█▊ ▝▘         
          ▔▔  ▔▔            `,
	`                            
                            
                            
                            
                            
                            
                            
             ▁    ▁▁        
       ▃     █▁▂▂▐█▍        
      ▕█▄▃▁▄▃▃▟████▙        
       ▔▔▜██████▛███▎       
       ▁ ▂█▛▎▀██▀▗▖▀        
       ▔▕▜█▍  ▐█▃           
         ▔▔▔  ▔▔▔           `,
	`                            
                            
                            
                            
                            
                            
                            
                   ▁        
       ▁     ▆▁  ▂▆▍        
      ▕█▁▁▁▁▁▝▗▆▇██▍        
       ▀▜▜▅█████████▎       
       ▂▅▟█▛▀███▖▐▛█▏       
       ▀█▊    ▔▜█▛▘         
        ▔▔      ▔           `,
}

// DogScottieWalkDelays contains the per-frame display durations.
var DogScottieWalkDelays = []time.Duration{
	180*time.Millisecond,
	180*time.Millisecond,
	180*time.Millisecond,
}
