// Code generated by tools/build-frames. DO NOT EDIT.
package ascii

import "time"

// GoatDarkWalkFrames contains the animation frames for the goat dark in walk state.
var GoatDarkWalkFrames = []string{
	`                            
                            
                            
                            
                            
                            
                ▗▄▖▄▄▄      
       ▁          ▁▁▀█▉     
      ▕█▃▁▂▃▃▃▃▁▂▃▆▎▁▔▔     
       ▀▜▇████████▙▖▁▄▄     
         ▝██████████▎▀▛▏    
         ▂██▍▔▀▀▀▀▜█▎       
        ▕▐▛        ▝▔       
         ▔          ▔       `,
	`                            
                            
                            
                            
                            
                            
                 ▜▍▀▇▇▄     
      ▕▅▁  ▁▁▁▁▁▁▁▄▅▁█▉     
      ▕██▆▆████▆▇█▛▘▀▘▖     
       ▔███████████▇▇██▋    
       ▕▉▘▝██▛██████▎▀▀     
       ▀▔▗▟██▏▀▀▔▐█▛▔       
         ▝█▍     ▐█▍        
          ▔       ▔         `,
	`                            
                            
                            
                            
                            
                            
                 ▜▍▀▇▇▄     
      ▕▅▁  ▁▁▁▁▁▁▁▄▅▁█▉     
      ▕██▆▆████▆▇█▛▘▀▘▖     
       ▔███████████▇▇██▋    
       ▕▉▘▝██▛██████▎▀▀     
       ▀▔▗▟██▏▀▀▔▐█▛▔       
         ▝█▍     ▐█▍        
          ▔       ▔         `,
}

// GoatDarkWalkDelays contains the per-frame display durations.
var GoatDarkWalkDelays = []time.Duration{
	180*time.Millisecond,
	180*time.Millisecond,
	180*time.Millisecond,
}
