// Code generated by tools/build-frames. DO NOT EDIT.
package ascii

import "time"

// GoatWhiteWalkFrames contains the animation frames for the goat white in walk state.
var GoatWhiteWalkFrames = []string{
	`                            
                            
                            
                            
                            
                            
                 ▗▖▄▄▄      
       ▁          ▁▁ █▊     
      ▕█▅▁▂▂▂▂▂▂▂▅▇▀        
       ▀██████████▙▃▃▃▆     
         ▝██████████▀▜▉     
         ▗██▍▀█▛▀▀▜█▎       
         ▜▛        ▀▏       
                            `,
	`                            
                            
                            
                            
                            
                            
                 ▝▘▀▜▇▃     
      ▕▅▁   ▁▁▁  ▁▄▅▁▜▀     
      ▕██▅▆▆▇▇▇▆▆█▛▘▔▔▂     
       ▔▀██████████▇▇▇▉     
       ▕▉▔▝██▛██████▎▝▀     
       ▔ ▗▟█▛▏▀▀ ▕█▍        
         ▝▜▌     ▝█▍        
                            `,
	`                            
                            
                            
                            
                            
                            
                 ▝▘▀▜▇▃     
      ▕▅▁   ▁▁▁  ▁▄▅▁▜▀     
      ▕██▅▆▆▇▇▇▆▆█▛▘▔▔▂     
       ▔▀██████████▇▇▇▉     
       ▕▉▔▝██▛██████▎▝▀     
       ▔ ▗▟█▛▏▀▀ ▕█▍        
         ▝▜▌     ▝█▍        
                            `,
}

// GoatWhiteWalkDelays contains the per-frame display durations.
var GoatWhiteWalkDelays = []time.Duration{
	180*time.Millisecond,
	180*time.Millisecond,
	180*time.Millisecond,
}
