// Code generated by tools/build-frames. DO NOT EDIT.
package ascii

import "time"

// GoatWhiteIdleFrames contains the animation frames for the goat white in idle state.
var GoatWhiteIdleFrames = []string{
	`                            
                            
                            
                            
                            
                            
                 ▝▘▀▜▇▃     
      ▕▅▁   ▁▁▁  ▁▄▅▁▜▀     
      ▕██▅▆▆▇▇▇▆▆█▛▘▔▔▂     
       ▔▀██████████▇▇▇▉     
       ▕▉▔▝██▛██████▎▝▀     
       ▔ ▗▟█▛▏▀▀ ▕█▍        
         ▝▜▌     ▝█▍        
                            `,
}

// GoatWhiteIdleDelays contains the per-frame display durations.
var GoatWhiteIdleDelays = []time.Duration{
	600*time.Millisecond,
}
