// Code generated by tools/build-frames. DO NOT EDIT.
package ascii

import "time"

// GoatDarkIdleFrames contains the animation frames for the goat dark in idle state.
var GoatDarkIdleFrames = []string{
	`                            
                            
                            
                            
                            
                            
                 ▜▍▀▇▇▄     
      ▕▅▁  ▁▁▁▁▁▁▁▄▅▁█▉     
      ▕██▆▆████▆▇█▛▘▀▘▖     
       ▔███████████▇▇██▋    
       ▕▉▘▝██▛██████▎▀▀     
       ▀▔▗▟██▏▀▀▔▐█▛▔       
         ▝█▍     ▐█▍        
          ▔       ▔         `,
}

// GoatDarkIdleDelays contains the per-frame display durations.
var GoatDarkIdleDelays = []time.Duration{
	600*time.Millisecond,
}
