// Code generated by tools/build-frames. DO NOT EDIT.
package ascii

import "time"

// HorseGrayIdleFrames contains the animation frames for the horse gray in idle state.
var HorseGrayIdleFrames = []string{
	`                            
                            
                 ▗▃    ▗▃   
                 ▐▌▄█▟▜█▋   
               ▕▅▟██▎█▟▊▘   
    ▃▃▃▃▃▖    ▅█▊▐▃▃▆███▖   
   ▐▘▔████▇▇▙▇▔▜▇████████▌  
  ▐▌  █████████████▍ ▀▀▀▘   
  ▝▘  ████████████▌         
      ▕██▊▀▀▀▀▔▝██▌         
   ▁  ▕██▘     ▕▟▋          
  ▐▌  ██       ▐█▋          
      █▉▃      ▕█▌▖         
       ▔▔       ▔▔          `,
}

// HorseGrayIdleDelays contains the per-frame display durations.
var HorseGrayIdleDelays = []time.Duration{
	600*time.Millisecond,
}
