// Code generated by tools/build-frames. DO NOT EDIT.
package ascii

import "time"

// HorseDarkEatFrames contains the animation frames for the horse dark in eat state.
var HorseDarkEatFrames = []string{
	`                            
                            
                            
                            
                            
    ▂▃▃▄▄▃▁ ▁▃▄▃▃▂          
   ▐▀▔█████▇▇▎█▀▛█▋▅▖       
  ▐▌▕▏███████████▄██▎▂▇█▊▏  
   ▕▁▏████████████▍▃▏█▟█▘   
  ▕▁▏ ▔███▀▀▀▀▔▝▜████▇█▊    
   ▁  ▟██▔   ▁ ▕█▛▔████▉▏   
  ▐▌  ██▔    ▔ ▐█▋ ▔███▉▏   
   ▀▀ ██▃    ▝▘▕█▙▖  ▔▀▘    
      ▔▔▔       ▔▔▔         `,
	`                            
                            
                            
                            
                            
    ▃▃▃▄▄▃▁ ▁▁▄▃▃▂          
   ▐▀▔█████▇▇██▀▛▚▖▅▅       
  ▐▌▕▏███████████▟██▎▂▇█▊▏  
  ▝▌▁▏████████████▍▞▎█▟█▘   
   ▕▏ ▔███▀▀▀▀▀▝█████▇█▊    
   ▁  ▗██▘   ▁ ▕▟▛▔████▉▏   
  ▐▌  ██▔    ▔ ▐█▋ ▔███▉▏   
   ▀▀ ██▃    ▝▘▕█▙▖  ▔▀▘    
      ▔▔▔       ▔▔▔         `,
	`                            
                            
                            
                            
                            
    ▃▃▃▄▄▃▁ ▁▁▁▃▃▁          
   ▐▋▔█████▇▇██▜█▍▁▅▖       
  ▐▛▏ ██████████▅▟██▎▂▇█▊▏  
  ▝▘▕▏▜████████████▂▁█▟█▘   
     ▕▕███▀▀▀▀▀▜█████▇█▊    
   ▁▏ ▕██▘   ▁ ▕▟▛▔████▉▏   
  ▐▌  ██▘    ▔ ▐█▋ ▔███▉▏   
   ▀▀ ██▃    ▝▘▕█▙▖  ▔▀▘    
      ▔▔▔       ▔▔▔         `,
}

// HorseDarkEatDelays contains the per-frame display durations.
var HorseDarkEatDelays = []time.Duration{
	400*time.Millisecond,
	400*time.Millisecond,
	400*time.Millisecond,
}
