// Code generated by tools/build-frames. DO NOT EDIT.
package ascii

import "time"

// HorsePalominoEatFrames contains the animation frames for the horse palomino in eat state.
var HorsePalominoEatFrames = []string{
	`                            
                            
                            
                            
                            
    ▂▃▃▃▃▖   ▃▃▃▃▂          
   ▝▘▔████▇▇▙▎█▀▀▜▌▄        
  ▐▌  ███████████▖▜█▏▁▟█▋   
      ████████████▂▂▏▀▃█▍   
      ▕██▊▀▀▀▘ ▔▜███▇▇█▊    
   ▁  ▄█▉▔     ▕█▋▔████▊    
  ▐▌  ██       ▐█▋  ▜▜█▊    
      ▝▉▃      ▕▜▙▖  ▔▘▔    
      ▔▔▔       ▔▔▔         `,
	`                            
                            
                            
                            
                            
    ▃▃▃▃▃▖    ▃▃▃▂          
   ▝▘▔████▇▇▙▛█▀▀▗▖▄▄       
  ▐▌  ███████████▞██▎▁▟█▋   
  ▝▘  ████████████▂▂▏▀▃█▍   
      ▕██▊▀▀▀▀▔▝████▇▇█▊    
   ▁  ▕██▘     ▕▟▋▔████▊    
  ▐▌  ██       ▐█▋  ▜▜█▊    
      █▉▃      ▕█▙▖  ▔▘▔    
      ▔▔▔       ▔▔▔         `,
	`                            
                            
                            
                            
                            
    ▃▃▃▃▃▖     ▃▂           
   ▐▍▔████▇▇▙▛▇▐█▘ ▄        
  ▐▌  ██████████▅▞██▎▁▟█▋   
  ▝▘  ▀███████████▞▂ ▜▃█▍   
      ▕██▊▀▀▀▀▔▐████▇▇█▊    
   ▁  ▕██▘     ▕▟▋▔████▊    
  ▐▌  ██▘      ▐█▋  ▜▜█▊    
      █▉▃      ▕█▙▖  ▔▘▔    
      ▔▔▔       ▔▔▔         `,
}

// HorsePalominoEatDelays contains the per-frame display durations.
var HorsePalominoEatDelays = []time.Duration{
	400*time.Millisecond,
	400*time.Millisecond,
	400*time.Millisecond,
}
