// Code generated by tools/build-frames. DO NOT EDIT.
package ascii

import "time"

// HorseBayIdleFrames contains the animation frames for the horse bay in idle state.
var HorseBayIdleFrames = []string{
	`                            
                            
                 ▗▃   ▁▗▃   
                 ▐▌▅█▟██▋   
               ▕▅▟██▎█▇▊▘   
    ▃▃▃▄▄▖▁  ▁▅█▊▐▙▃▆███▖   
   ▐▘▔█████▇▆▇▝▜▇████████▌  
  ▐▌▕▏█████████████▍ ▀▀▀▀▔  
  ▝▘▁▏████████████▌         
   ▕▏ ▕██▊▀▀▀▀▘▝██▌         
   ▁  ▕██▘     ▕▟▉▏         
  ▐▌  ██       ▐█▋          
      ██▃      ▕█▙▖         
      ▔▔▔       ▔▔▔         `,
}

// HorseBayIdleDelays contains the per-frame display durations.
var HorseBayIdleDelays = []time.Duration{
	600*time.Millisecond,
}
