// Code generated by tools/build-frames. DO NOT EDIT.
package ascii

import "time"

// HorsePalominoWalkFrames contains the animation frames for the horse palomino in walk state.
var HorsePalominoWalkFrames = []string{
	`                            
                            
                            
                 ▐▌▁▄▁▄▟▋   
                ▂▗▅█▀▉▐█▍   
               ▃▉▜▀▀▃▆█▊    
    ▟▇▇▇▇▇▄▄▖▄▜▉▗▟▇▇████▇▖  
    ▜████████▅▅▇███▍▀███▛▘  
    ▐█████████████▛         
    ▗███▜█████▛███▌         
  ▗▄██▀▔  ▔▔▔   ▐█▙▖        
  ▐█▛▏       ▁   ▐█▍        
   ▐▆▎       ▔    ▐▇▏       
                            `,
	`                            
                            
                 ▗▃    ▗▃   
                 ▝▘▄█▅▜█▀   
               ▕▅▟██▎▂▟▊▘   
    ▃▃▃▃▃▖    ▃█▋▝▃▃▆██▊▖   
   ▝▘▔████▇▇▙▛▔▜▟▇█▛█████▌  
  ▐▌  █████████████▍ ▀▀▀▀   
  ▝▘  ████████████▌         
      ▕██▊▀▀▀▀▔▝██▌         
   ▁  ▕██▘     ▕▟▋          
  ▐▌  ██       ▐█▋          
      █▉▃      ▕█▙▖         
      ▔▔▔       ▔▔▔         `,
	`                            
                            
                            
                 ▐▌▁▄▁▄▟▋   
                ▂▗▅█▀▉▐█▍   
               ▃▉▜▀▀▃▆█▊    
   ▗▞▜▇▇▇▇▄▄▖▄▜▉▗▟▇▇████▇▖  
  ▗▖  ███████▅▅▇███▍▀███▛▘  
  ▝▘  ▕███████████▛▏        
       ▀█████████▛▔         
       ▕██▌ ▔ ▟█▊           
 ▕▋    ▕█▊   ▅█▉            
  ▔    ▕▜▋▖  ▆▉             
         ▔▔  ▔▔             `,
}

// HorsePalominoWalkDelays contains the per-frame display durations.
var HorsePalominoWalkDelays = []time.Duration{
	180*time.Millisecond,
	180*time.Millisecond,
	180*time.Millisecond,
}
