// Code generated by tools/build-frames. DO NOT EDIT.
package ascii

import "time"

// PigPinkIdleFrames contains the animation frames for the pig pink in idle state.
var PigPinkIdleFrames = []string{
	`                            
                            
                            
                            
                            
                            
                            
      ▕█▜▋ ▁▁▁▁  ▗▖▁▅▅      
       ▘▆▆▆████▆▆▆▆██▉      
       ▕███████████▙▃▃      
       ▕▜███▛████████▙▄     
         ▐▛▀ ▀▀▝▀ ▝▜▎▀▀     
        ▕▃▖    ▕▅▌          
         ▔▔     ▔▔          `,
}

// PigPinkIdleDelays contains the per-frame display durations.
var PigPinkIdleDelays = []time.Duration{
	600*time.Millisecond,
}
