// Code generated by tools/build-frames. DO NOT EDIT.
package ascii

import "time"

// PigletPinkWalkFrames contains the animation frames for the piglet pink in walk state.
var PigletPinkWalkFrames = []string{
	`                            
                            
                            
                            
                            
                            
                            
                            
                            
              ▘▁▟▇▌         
       ▀▜▄▄▄▄▄███▀          
       ▇█████████▌          
       ▃▛▘▔▀▀█▔▝▀▀▘         
       ▔     ▔              `,
	`                            
                            
                            
                            
                            
                            
                            
                            
              ▂ ▂▂▂         
       ▃▃     ▃▅██▍         
       ▔▟████████▌          
       ▕██▛▜██▀██▙▖         
        ▕▃▎ ▂▁ ▔▔▔          
         ▔  ▔▔              `,
	`                            
                            
                            
                            
                            
                            
                            
                            
                            
              ▘▁▟▇▌         
       ▀▀▗▄▄▄▄███▀          
        ▐████████▌          
        ▔▀▜▚▝▀▔▀▀▀▘         
           ▔▔               `,
}

// PigletPinkWalkDelays contains the per-frame display durations.
var PigletPinkWalkDelays = []time.Duration{
	180*time.Millisecond,
	180*time.Millisecond,
	180*time.Millisecond,
}
