// Code generated by tools/build-frames. DO NOT EDIT.
package ascii

import "time"

// PigletPinkIdleFrames contains the animation frames for the piglet pink in idle state.
var PigletPinkIdleFrames = []string{
	`                            
                            
                            
                            
                            
                            
                            
                            
              ▂ ▂▂▂         
       ▃▃     ▃▅██▍         
       ▔▟████████▌          
       ▕██▛▜██▀██▙▖         
        ▕▃▎ ▂▁ ▔▔▔          
         ▔  ▔▔              `,
}

// PigletPinkIdleDelays contains the per-frame display durations.
var PigletPinkIdleDelays = []time.Duration{
	600*time.Millisecond,
}
