// Code generated by tools/build-frames. DO NOT EDIT.
package ascii

import "time"

// SheepFluffyIdleFrames contains the animation frames for the sheep fluffy in idle state.
var SheepFluffyIdleFrames = []string{
	`                            
                            
                            
                            
                            
                            
                            
      ▁▁▄▅▅▅▅▅▅▂▁▁▗▅▅▅▁     
     ▂████████████▂▝▀█▂     
     ██████████████▍▄▃▔     
     ▀▏▐██████████▛▎▜█      
      ▔ ▔▐▛▀▀▀██▛▀          
         ▐▌     ▕▍          
                            `,
}

// SheepFluffyIdleDelays contains the per-frame display durations.
var SheepFluffyIdleDelays = []time.Duration{
	600*time.Millisecond,
}
