// Code generated by tools/build-frames. DO NOT EDIT.
package ascii

import "time"

// SheepWoollyWalkFrames contains the animation frames for the sheep woolly in walk state.
var SheepWoollyWalkFrames = []string{
	`                            
                            
                            
                            
                            
                            
                            
                            
                  ▂▂▂▂      
        ▟▇▇▇▇▅▄▃▃▟███▀▀     
        ▔▐████████▌▄██      
        ▂▟█▛▀▀▀▀▜█▙▔▀▀      
        ▐▛▔      ▝▀▏        
                            `,
	`                            
                            
                            
                            
                            
                            
                            
                            
        ▂▂▂▂▂▁▁  ▂▆▆▆▆▂     
       ▕▜▜█████▇▇██▜█▙▔     
          ▜█▛████▉▔▜██      
         ▐█▌   ▝▜▛▘         
         ▐▌    ▕▐▋          
                            `,
	`                            
                            
                            
                            
                            
                            
                            
                            
                   ▂▂▂▂     
        ▗▟▇▇▇▇▅▄▃▃▇███▀▘    
         ▔▔███████▛▀▟█▉     
           ▜██▏▕▟▛▘ ▔▀▀     
            ▜▏ ▝▛▔          
                            `,
}

// SheepWoollyWalkDelays contains the per-frame display durations.
var SheepWoollyWalkDelays = []time.Duration{
	180*time.Millisecond,
	180*time.Millisecond,
	180*time.Millisecond,
}
