// Code generated by tools/build-frames. DO NOT EDIT.
package ascii

import "time"

// SheepFluffyWalkFrames contains the animation frames for the sheep fluffy in walk state.
var SheepFluffyWalkFrames = []string{
	`                            
                            
                            
                            
                            
                            
                            
         ▁▁▁▁▁▁▁   ▁▁▁▁     
       ▕▆▇██████▆▅▂▝▜██▘    
      ▄█▟██████████▍ ▕▀▘    
      ▜▔▀██████████▌▏█▉     
       ▔ ▝▀▜██████▛▘ ▔▀     
           ▐▎  ▕▘           
                            `,
	`                            
                            
                            
                            
                            
                            
                            
      ▁▁▄▅▅▅▅▅▅▂▁▁▗▅▅▅▁     
     ▂████████████▂▝▀█▂     
     ██████████████▍▄▃▔     
     ▀▏▐██████████▛▎▜█      
      ▔ ▔▐▛▀▀▀██▛▀          
         ▐▌     ▕▍          
                            `,
	`                            
                            
                            
                            
                            
                            
                            
        ▁▁▁▁▁▁▁▁  ▁▁▁▁      
      ▆▆████████▆▅▞▜██▘     
     ▇█████████████▍▁▀▀     
     ▔▜████████████▍██      
      ▔▀▜███▛▀▀███▌ ▔▀      
       ▕▖       ▝▘          
                            `,
}

// SheepFluffyWalkDelays contains the per-frame display durations.
var SheepFluffyWalkDelays = []time.Duration{
	180*time.Millisecond,
	180*time.Millisecond,
	180*time.Millisecond,
}
