// Code generated by tools/build-frames. DO NOT EDIT.
package ascii

import "time"

// SheepGrayIdleFrames contains the animation frames for the sheep gray in idle state.
var SheepGrayIdleFrames = []string{
	`                            
                            
                            
                            
                            
                            
                            
      ▁▁▄▅▅▅▅▅▅▂▁▁▗▅▅▅▁     
     ▂████████████▂▝▀▀▘     
     ██████████████▍ ▔      
     ▀▏▐██████████▛▎ ▔      
        ▔▝▀▀▀▀██▛▀          
                            
                            `,
}

// SheepGrayIdleDelays contains the per-frame display durations.
var SheepGrayIdleDelays = []time.Duration{
	600*time.Millisecond,
}
