// Code generated by tools/build-frames. DO NOT EDIT.
package ascii

import "time"

// TurkeyBrownWalkFrames contains the animation frames for the turkey brown in walk state.
var TurkeyBrownWalkFrames = []string{
	`                            
                            
                            
                            
                            
                            
                            
                            
        ▗▆▆▖ ▂▂▂▂▂▂         
       ▕██▛▚▇█▀██▛▜▍        
        ▔▜▌█▛▀▉▕▋▐▛█▎       
       ▕█▋  ▝█▅  ▗▝▏        
        ▐▋  ▔▆▆  ▆▛▎        
         ▔   ▔▔  ▔▔         `,
	`                            
                            
                            
                            
                            
                            
                            
         ▁▁▁                
        ▟██▌▂▆▆▆▆▆▅▂        
       ▝▜█▋▅██▃▜▛▚█▙        
       ▗▄▞▘▀▚▄▀ ▘▝▚▀▏       
       ▕█▋  ▗▂▀▁ ▂▚▖        
         ▗▖ ▃▃▛▀▝▜▀         
         ▔▔ ▔▔              `,
	`                            
                            
                            
                            
                            
                            
                            
                            
        ▗▆▆▖ ▂▂▂▂▂▂         
       ▕██▛▚▇█▀██▛▜▍        
        ▔▜▌█▛▀▉▕▋▐▛█▎       
       ▕█▋  ▝█▅  ▗▝▏        
        ▝▚▖▃▔▆▆  ▆▛▎        
           ▔ ▔▔  ▔▔         `,
}

// TurkeyBrownWalkDelays contains the per-frame display durations.
var TurkeyBrownWalkDelays = []time.Duration{
	180*time.Millisecond,
	180*time.Millisecond,
	180*time.Millisecond,
}
